---
title: "Raúl"
output:
  html_document: default
  pdf_document: default
---

```{r}
col_manhattan <- "green" 
col_euclidean <- "magenta" 
col_chebyshev <- "blue" 
col_unknown_class <- "red"
col_nearest <- "black"
col_no_nearest <- "grey"
```

```{r echo=FALSE}
library(tidyverse)
library(ggforce)
```

```{r echo=FALSE}
# Manhttan -> de más cercano a más lejano, A-B-D-C
# Euclídea y Chebyshev -> A-B-C-D.

data <- tribble(~x, ~y, ~name, ~class,
                0, 0, "", "to_classify",
                1, 0, "A", "circle",
                1, 2, "B", "triangle",
                3, 2, "C", "circle",
                0, 4, "D", "triangle")
data$class <- factor(data$class, levels = c("circle", "triangle", "to_classify"))
#rownames(data) <- c("x", letters[1:4])

```

```{r echo=FALSE}
circleFun <- function(center = c(0,0),diameter = 2, npoints = 100){
    r = diameter / 2
    tt <- seq(0,2*pi,length.out = npoints)
    xx <- center[1] + r * cos(tt)
    yy <- center[2] + r * sin(tt)
    return(data.frame(x = xx, y = yy))
}
circle <- circleFun(c(0,0), 7.2, npoints = 100)
```

```{r echo=FALSE}
manhattan <- tibble(x = c(0,-4,0,4), y = c(4,0,-4,0))
```

# The points

Given a dataset...

```{r echo=FALSE}
ggplot(data[-1,], aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  geom_point(size = 8, shape = 4)  +
  theme_minimal() +
  theme(legend.position="none") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

Of known classes...

```{r echo=FALSE}
ggplot(data[-1,], aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  #scale_shape_manual(values=c(1, 2, 4)) + #figuras sin relleno
  scale_shape_manual(values=c(16, 17, 4)) +
  geom_point(aes(shape = class), size = 8)  +
  theme_minimal() +
  theme(legend.position="none") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

Now we want to classify a new instance...

```{r echo=FALSE}
ggplot(data, aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  #scale_shape_manual(values=c(1, 2, 4)) + #figuras sin relleno
  scale_shape_manual(values=c(16, 17, 4)) +
  geom_point(aes(shape = class), size = 8, col=c(col_unknown_class, rep("black", 4)))  +
  theme_minimal() +
  theme(legend.position="none") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r echo=FALSE}
ggplot(data, aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  #scale_shape_manual(values=c(1, 2, 4)) + #figuras sin relleno
  scale_shape_manual(values=c(16, 17, 4)) +
  geom_point(aes(shape = class), size = 8, col=c(col_unknown_class, rep("black", 4)))  +
  geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4.5) +
  theme_minimal() +
  theme(legend.position="none") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

# Manhattan distance

```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Manhattan
  #geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  #geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0.2, linetype = "twodash") +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0.2, linetype = "twodash") +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0.2, linetype = "twodash") +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4) +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

# Euclidean distance

```{r}
ggplot() +
  
  # Euclidean
  geom_circle(aes(x0 = 0, y0 = 0, r = 1),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(5)),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = 3.5),  color=col_euclidean, linetype = "dotted", fill = "black", alpha=0) +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Euclidean
  #geom_circle(aes(x0 = 0, y0 = 0, r = 1),  color=col_euclidean, linetype = "dotted") +
  #geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(5)),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(13)),  color=col_euclidean, linetype = "dotted", fill = "black", alpha=0.2) +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Euclidean
  geom_circle(aes(x0 = 0, y0 = 0, r = 1),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(5)),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(13)),  color=col_euclidean, linetype = "dotted", fill = "black", alpha=0.2) +
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4) +
  
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

# Chebyshev

```{r}
ggplot() +
  
  # Chebyshev
  geom_rect(aes(xmin=-1, ymin=-1, xmax=1, ymax=1), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-2, ymin=-2, xmax=2, ymax=2), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
 
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Chebyshev
  geom_rect(aes(xmin=-1, ymin=-1, xmax=1, ymax=1), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-2, ymin=-2, xmax=2, ymax=2), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", color=col_chebyshev, alpha=0.2, linetype = "longdash") +
 
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4) +
  
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

# All

```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  
  # Euclidean
  geom_circle(aes(x0 = 0, y0 = 0, r = 1),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(5)),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(13)),  color=col_euclidean, linetype = "dotted", fill = "black", alpha=0) +
  
  # Chebyshev
  geom_rect(aes(xmin=-1, ymin=-1, xmax=1, ymax=1), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-2, ymin=-2, xmax=2, ymax=2), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
 
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
   geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4) +
 
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```


```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  
  # Euclidean
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(13)),  color=col_euclidean, linetype = "dotted", fill = "black", alpha=0) +
  
  # Chebyshev
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
 
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
   geom_text(aes(x, y, label = name), data = data, color = "white", fontface = "bold", size = 4) +
 
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```

```{r}
ggplot() +
  
  # Manhattan
  geom_polygon(aes(x=c(-1,0,1,0), y = c(0,1,0,-1), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-3,0,3,0), y = c(0,3,0,-3), linetype = b), fill = "black", col=col_manhattan, alpha=0, linetype = "twodash") +
  geom_polygon(aes(x=c(-4,0,4,0), y = c(0,4,0,-4), linetype = b), fill = col_manhattan, col=col_manhattan, alpha=0.1, linetype = "twodash") +
  
  # Euclidean
  geom_circle(aes(x0 = 0, y0 = 0, r = 1),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(5)),  color=col_euclidean, linetype = "dotted") +
  geom_circle(aes(x0 = 0, y0 = 0, r = sqrt(13)),  color=col_euclidean, linetype = "dotted", fill = col_euclidean, alpha=0.1) +
  
  # Chebyshev
  geom_rect(aes(xmin=-1, ymin=-1, xmax=1, ymax=1), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-2, ymin=-2, xmax=2, ymax=2), fill = "black", color=col_chebyshev, alpha=0, linetype = "longdash") +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = col_chebyshev, color=col_chebyshev, alpha=0.1, linetype = "longdash") +
 
  
  # Plot
  geom_point(aes(x, y, shape = class), data = data, size = 8, col=c(col_unknown_class, rep("black", 4)), alpha = 0.9)  +
  scale_shape_manual(values=c(16, 17, 4)) +
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_colour_manual(values = c(col_euclidean, col_manhattan, col_chebyshev)) +
  coord_fixed() +
  theme_light() +
  theme(legend.position = "none") +
  xlab("x") +
  ylab("y") +    
  theme(axis.title.y = element_text(angle = 0, vjust = 0.5)) 
```


# Ejemplo 3

```{r echo=FALSE}
ggplot(data, aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  geom_polygon(data = circle, fill = "black", col = col_euclidean, alpha = 0) +
  geom_polygon(data = manhattan, fill = "black", col = col_chebyshev, alpha = 0) +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", col=col_manhattan, alpha=0) +
  geom_point(aes(shape = class), size = 6)  +
  theme_minimal() +
  theme(legend.position="none")
```

# V1: Remarcados A, B y D

```{r echo=FALSE}
data <- data %>% mutate(highlight = name %in% c("A","D","B"))
ggplot(data, aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  geom_polygon(data = circle, fill = "black", col = col_euclidean, alpha = 0) +
  geom_polygon(data = manhattan, fill = "black", col = col_chebyshev, alpha = 0) +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", col=col_manhattan, alpha=0) +
  geom_point(aes(shape = class, col = highlight), size = 6)  +
  theme_minimal() +
  theme(legend.position="none") + 
  scale_col_manual(values=c(col_unknown_class, col_nearest))
```

# V2: Remarcados A, B y C. 

```{r echo=FALSE}
data <- data %>% mutate(highlight = name %in% c("A","C","B"))
ggplot(data, aes(x, y)) + 
  scale_x_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  scale_y_continuous(limits = c(-4.5, 4.5), breaks = -5:5) +
  coord_fixed() +
  geom_polygon(data = circle, fill = "black", col = col_euclidean, alpha = 0) +
  geom_polygon(data = manhattan, fill = "black", col = col_chebyshev, alpha = 0) +
  geom_rect(aes(xmin=-3, ymin=-3, xmax=3, ymax=3), fill = "black", col=col_manhattan, alpha=0) +
  geom_point(aes(shape = class, col = highlight), size = 6)  +
  theme_minimal() +
  theme(legend.position="none") + 
  scale_col_manual(values=c(col_unknown_class, col_nearest))
```