---
title: "R Notebook"
output: html_notebook
---


# Untidying

```{r}
set.seed(123)
v1 <- c(1, 4, 6, 2, 3, 4, 9, 7, 6, 1, 8, 5)
names(v1) <- sample(c("circle", "square"), 12, replace = TRUE)
r1 <- ranking(v1)
r2 <- ranking(c(6, 4, 1, 3, 3, 8, 9, 7, 6, 5, 8, 2))
```

```{r}
chooseBest(r1, "randomly", 3)
```


```{r include=FALSE}
library(tidyverse)
library(caret)
library(knitr)
library(kableExtra)
```

```{r}
set.seed(123)
indexes <- createDataPartition(iris$Species, times = 1, p = 0.08, list = FALSE)
mini_iris <- iris[indexes,]
```

```{r}
knn4Train(train =  mini_iris[,-5],
          cl = mini_iris[,5],
          )
```


```{r}
set.seed(123)
mini_iris <- as.data.frame(mini_iris)
fit <- train(x =  mini_iris[,-5],
      y = mini_iris[,5],
      data = mini_iris,
      method = rknn,
      trControl = fitControl)
```

```{r}
data <- fit$modelInfo$grid()
kable(data) %>%
  kable_styling("striped", full_width = F) %>%
  row_spec(which(data$k == 3), bold = T, color = "black", background = "#fdfd96")
```

```{r}

```


# rknn

- For each element in the test set
-- For each distance: 
---- calculate the distance: create a ranking
-- create a profile of rankings
-- apply ranking rule
-- choose the label 




# dknn
